version: '3.5'

services:

  cm-api:
    container_name: cm
    build: .
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/index
    environment:
    - NODE_ENV=production
    - DATABASE_URL=${DATABASE_URL}
    command: sh -c "npm run prisma && node build/index.js"

  postgres:
    container_name: postgres-cm
    image: postgres
    environment:
      # - POSTGRES_USER=cmuser
      - POSTGRES_PASSWORD=cmpassword
    volumes:
      - ./data:/data/postgres
    ports:
      - "5435:5432"
    expose:
      - 5432